# Generated by Django 6.0.7 on 2026-07-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('composer', models.CharField(blank=True, max_length=500)),
                ('imslp_url', models.URLField(max_length=1000, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('instrumentation', models.CharField(blank=True, max_length=500)),
                ('type', models.CharField(max_length=50)),
                ('movement', models.CharField(blank=True, max_length=500, null=True)),
                ('arranger', models.CharField(blank=True, max_length=500, null=True)),
                ('editor', models.CharField(blank=True, max_length=500, null=True)),
                ('imslp_url', models.URLField(max_length=1000)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.work')),
            ],
        ),
    ]
