# Generated by Django 6.0.7 on 2026-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
