# Generated by Django 6.1.1 on 2026-09-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_version_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pdf_path', models.CharField(max_length=1000, unique=True)),
                ('enhanced_pdf_path', models.CharField(blank=True, max_length=1000)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('time_signature', models.CharField(blank=True, max_length=20)),
                ('piece_data', models.JSONField(default=dict)),
                ('bar_boxes', models.JSONField(default=list)),
                ('timing', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('page_png_path', models.CharField(blank=True, max_length=1000)),
                ('debug_png_path', models.CharField(blank=True, max_length=1000)),
                ('markings_debug_png_path', models.CharField(blank=True, max_length=1000)),
                ('musicxml', models.TextField(blank=True)),
                ('notes_json', models.JSONField(default=dict)),
                ('markings_json', models.JSONField(default=list)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.processedscore')),
            ],
            options={
                'ordering': ['page_number'],
                'constraints': [models.UniqueConstraint(fields=('score', 'page_number'), name='uniq_score_page')],
            },
        ),
    ]
