// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initSession({required String jsonData}) =>
    RustLib.instance.api.crateApiInitSession(jsonData: jsonData);

Future<String> getUserData() => RustLib.instance.api.crateApiGetUserData();

Stream<List<Notes>> notesStream() => RustLib.instance.api.crateApiNotesStream();

/// TEST ONLY. Pushes an already-detected phrase straight into the
/// notes_stream sink, so the Dart side receives it exactly as if the
/// microphone and pitch detection had produced it.
///
/// This exists so the Rust -> Dart -> Python -> Dart round trip can be
/// exercised without working audio capture. It deliberately does not
/// touch `listen_audio`, `stop_audio` or any part of the real capture
/// path -- it only borrows the same sink those would ultimately feed.
///
/// `json_data` is the sample payload used by the Python backend (see
/// backend/feedback_generator/sample_data/phrase_imperfect.json); the
/// `user_notes` array is what gets injected. Fields the real `Notes`
/// struct carries but that sample omits (`is_end` and the optional
/// expressive ones) default rather than failing to parse.
///
/// Returns a status string instead of panicking, because an unwrap here
/// would abort across the FFI boundary and take the app down.
Future<String> injectTestPhrase({required String jsonData}) =>
    RustLib.instance.api.crateApiInjectTestPhrase(jsonData: jsonData);
