// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Notes {
  final BigInt noteId;
  final double pitchHz;
  final double? startTimeMs;
  final double? endTimeMs;
  final double? durationMs;
  final bool isEnd;
  final double? vibratoDepth;
  final String? pedalAction;
  final bool? hasAccent;
  final String? markings;

  /// How loudly the note was played: 0.0 (at or below -60 dBFS) to 1.0
  /// (full scale), spaced in decibels (see volume.rs). The loudest 50 ms
  /// of the note's span. Relative to this microphone and device, not a
  /// calibrated level, so mapping it to pp..ff is the backend's job.
  /// `None` on score notes, and on a played note whose audio isn't logged.
  final double? volume;

  const Notes({
    required this.noteId,
    required this.pitchHz,
    this.startTimeMs,
    this.endTimeMs,
    this.durationMs,
    required this.isEnd,
    this.vibratoDepth,
    this.pedalAction,
    this.hasAccent,
    this.markings,
    this.volume,
  });

  @override
  int get hashCode =>
      noteId.hashCode ^
      pitchHz.hashCode ^
      startTimeMs.hashCode ^
      endTimeMs.hashCode ^
      durationMs.hashCode ^
      isEnd.hashCode ^
      vibratoDepth.hashCode ^
      pedalAction.hashCode ^
      hasAccent.hashCode ^
      markings.hashCode ^
      volume.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Notes &&
          runtimeType == other.runtimeType &&
          noteId == other.noteId &&
          pitchHz == other.pitchHz &&
          startTimeMs == other.startTimeMs &&
          endTimeMs == other.endTimeMs &&
          durationMs == other.durationMs &&
          isEnd == other.isEnd &&
          vibratoDepth == other.vibratoDepth &&
          pedalAction == other.pedalAction &&
          hasAccent == other.hasAccent &&
          markings == other.markings &&
          volume == other.volume;
}
