"""Shorthand constructors used by every era bank.

Banks are hand-written rather than generated by a language model on purpose:
this is exam-prep content, where a plausible-sounding wrong date or
misattributed composer is worse than no question at all. These two helpers
keep each entry to a few readable lines so the banks stay reviewable.
"""

from ..models import FILL_BLANK, LEVEL_ARCT, LEVEL_CORE, MULTIPLE_CHOICE, Question


def mc(qid, category, prompt, choices, answer, explanation, level=LEVEL_CORE):
    """A multiple-choice question. `answer` must appear in `choices`; that is
    asserted here so a typo in a bank fails at import rather than silently
    producing a question nobody can get right."""
    assert answer in choices, f"{qid}: answer {answer!r} missing from choices"
    return Question(
        id=qid,
        kind=MULTIPLE_CHOICE,
        category=category,
        prompt=prompt,
        choices=list(choices),
        answer=answer,
        explanation=explanation,
        level=level,
    )


def fb(qid, category, prompt, answer, explanation, accepted=(), level=LEVEL_CORE):
    """A fill-in-the-blank. `accepted` lists alternate spellings the grader
    should also allow (accents dropped, surname only, and so on)."""
    return Question(
        id=qid,
        kind=FILL_BLANK,
        category=category,
        prompt=prompt,
        choices=[],
        answer=answer,
        accepted=list(accepted),
        explanation=explanation,
        level=level,
    )


__all__ = ["mc", "fb", "LEVEL_ARCT", "LEVEL_CORE"]
