"""The Baroque era, 1600 - 1750."""

from ..models import (
    CATEGORY_COMPOSERS as C,
    CATEGORY_CONTEXT as X,
    CATEGORY_FORMS as F,
    CATEGORY_TERMS as T,
)
from ._builders import LEVEL_ARCT as A, fb, mc

QUESTIONS = [
    mc("ba-c01", C,
       "Which composer's L'Orfeo (1607) is the earliest opera still regularly staged?",
       ["Claudio Monteverdi", "Jacopo Peri", "Giulio Caccini", "Heinrich Schutz"],
       "Claudio Monteverdi",
       "Peri's Dafne came earlier but survives only in fragments."),
    mc("ba-c02", C,
       "Which Venetian priest wrote The Four Seasons and taught at the Ospedale della Pieta?",
       ["Antonio Vivaldi", "Arcangelo Corelli", "Domenico Scarlatti", "Tomaso Albinoni"],
       "Antonio Vivaldi",
       "Known as il prete rosso, 'the red priest', for his hair."),
    mc("ba-c03", C,
       "J. S. Bach spent the last 27 years of his life as Thomaskantor in which city?",
       ["Leipzig", "Weimar", "Kothen", "Hamburg"],
       "Leipzig",
       "From 1723 he was responsible for music at the Thomasschule and the city's principal churches."),
    mc("ba-c04", C,
       "Handel's Messiah was first performed in 1742 in which city?",
       ["Dublin", "London", "Hamburg", "Rome"],
       "Dublin",
       "It was written for a charity benefit and only later became a London fixture."),
    mc("ba-c05", C,
       "Which composer dominated French court music under Louis XIV?",
       ["Jean-Baptiste Lully", "Francois Couperin", "Jean-Philippe Rameau", "Marc-Antoine Charpentier"],
       "Jean-Baptiste Lully",
       "Lully died of gangrene after striking his foot with the staff used to beat time."),
    mc("ba-c06", C,
       "Domenico Scarlatti is best known for over 550 works in which genre?",
       ["Keyboard sonatas", "Organ fugues", "Opera seria", "Concerti grossi"],
       "Keyboard sonatas",
       "Mostly single-movement binary works written for the Spanish court.",
       level=A),
    fb("ba-c07", C,
       "The composer of the treatise Traite de l'harmonie (1722), which founded modern harmonic theory, was Jean-Philippe ______.",
       "Rameau",
       "Rameau's theory of the fundamental bass underlies how we still label chords.",
       accepted=("rameau", "jean-philippe rameau"), level=A),

    mc("ba-f01", F,
       "A concerto grosso contrasts a small group of soloists, the concertino, against the full ensemble, the:",
       ["Ripieno", "Continuo", "Obbligato", "Tutti soli"],
       "Ripieno",
       "Also called the concerto grosso proper; Corelli standardized the form."),
    mc("ba-f02", F,
       "In a da capo aria the singer:",
       ["Repeats the A section with added ornamentation", "Sings three new sections", "Alternates with the chorus", "Speaks the final section"],
       "Repeats the A section with added ornamentation",
       "ABA form, where the repeat was the singer's chance to display invention."),
    mc("ba-f03", F,
       "A Baroque suite is a collection of:",
       ["Stylized dances", "Fugues", "Opera overtures", "Sacred motets"],
       "Stylized dances",
       "The core four are allemande, courante, sarabande and gigue."),
    mc("ba-f04", F,
       "An oratorio differs from an opera principally in that it:",
       ["Is unstaged and usually sacred", "Uses no orchestra", "Is always in Latin", "Has no soloists"],
       "Is unstaged and usually sacred",
       "No sets or costumes; the chorus carries far more of the drama."),
    mc("ba-f05", F,
       "Which form is built on a short repeating bass line?",
       ["Passacaglia", "Ritornello", "Rondeau", "Chorale prelude"],
       "Passacaglia",
       "Closely related to the chaconne; both are continuous-variation forms."),
    mc("ba-f06", F,
       "In a fugue, the answer is the subject restated:",
       ["At the dominant", "In inversion", "Twice as slow", "By the bass alone"],
       "At the dominant",
       "A tonal answer adjusts intervals to stay in key; a real answer transposes exactly."),

    mc("ba-t01", T,
       "Basso continuo consists of a bass line played by a sustaining instrument together with:",
       ["A chordal instrument realizing figures", "A second melody instrument", "Percussion", "A solo voice"],
       "A chordal instrument realizing figures",
       "Typically cello or bassoon with harpsichord or organ filling in the harmony."),
    mc("ba-t02", T,
       "Figured bass numerals indicate:",
       ["Intervals above the bass note", "Fingering", "Dynamics", "Tempo"],
       "Intervals above the bass note",
       "A 6 means a first-inversion chord; the player improvises the voicing."),
    mc("ba-t03", T,
       "The Doctrine of the Affections held that a movement should:",
       ["Express one prevailing emotion throughout", "Change mood constantly", "Avoid emotion entirely", "Follow the text word by word"],
       "Express one prevailing emotion throughout",
       "Hence the uniform texture and rhythmic drive of most Baroque movements."),
    mc("ba-t04", T,
       "Terraced dynamics means:",
       ["Abrupt shifts between loud and soft", "Gradual crescendo", "Dynamics left to the performer", "Constant volume"],
       "Abrupt shifts between loud and soft",
       "A consequence of instruments like the harpsichord, which cannot swell a note.",
       level=A),
    mc("ba-t05", T,
       "Recitative differs from aria in that it:",
       ["Follows speech rhythm to advance the plot", "Is always accompanied by full orchestra", "Repeats its opening section", "Is sung by the chorus"],
       "Follows speech rhythm to advance the plot",
       "Secco recitative is supported only by continuo; accompagnato adds strings."),
    fb("ba-t06", T,
       "The tuning system Bach explored in The Well-Tempered Clavier, allowing play in all keys, is called ______ temperament.",
       "well",
       "Well temperament is not the same as modern equal temperament; each key retained its own colour.",
       accepted=("well", "well temperament", "good"), level=A),

    mc("ba-x01", X,
       "The word 'baroque' originally meant:",
       ["An irregularly shaped pearl", "A royal dance", "A church mode", "A type of organ"],
       "An irregularly shaped pearl",
       "It began as a term of abuse for art thought overwrought."),
    mc("ba-x02", X,
       "Baroque musicians were most commonly employed by:",
       ["Courts, churches and opera houses", "Public subscription concerts", "Recording companies", "Universities"],
       "Courts, churches and opera houses",
       "Composers were salaried servants; Bach's Leipzig contract listed teaching duties too."),
    mc("ba-x03", X,
       "The Baroque era is conventionally dated from 1600 to 1750, the latter being the year of:",
       ["Bach's death", "Handel's birth", "The first opera", "Vivaldi's death"],
       "Bach's death",
       "A convenient marker rather than a real stylistic break - galant style was already ascendant."),
    mc("ba-x04", X,
       "Which family of Cremona violin makers shaped the modern instrument?",
       ["Stradivari", "Ruckers", "Silbermann", "Broadwood"],
       "Stradivari",
       "Antonio Stradivari worked alongside the Amati and Guarneri workshops."),
]
