"""The Classical era, 1750 - 1825."""

from ..models import (
    CATEGORY_COMPOSERS as C,
    CATEGORY_CONTEXT as X,
    CATEGORY_FORMS as F,
    CATEGORY_TERMS as T,
)
from ._builders import LEVEL_ARCT as A, fb, mc

QUESTIONS = [
    mc("cl-c01", C,
       "Which composer, long employed by the Esterhazy family, is called the father of the symphony?",
       ["Joseph Haydn", "W. A. Mozart", "C. P. E. Bach", "Luigi Boccherini"],
       "Joseph Haydn",
       "Nearly 30 years at Esterhaza let Haydn experiment with an orchestra of his own."),
    mc("cl-c02", C,
       "Mozart's last three symphonies, Nos. 39-41, were all composed in:",
       ["1788", "1781", "1791", "1785"],
       "1788",
       "Written in about six weeks; No. 41 is nicknamed 'Jupiter'."),
    mc("cl-c03", C,
       "Which Beethoven symphony first adds voices to the symphonic finale?",
       ["No. 9", "No. 5", "No. 3", "No. 6"],
       "No. 9",
       "The 1824 finale sets Schiller's An die Freude for soloists and chorus."),
    mc("cl-c04", C,
       "Beethoven's Symphony No. 3 was originally dedicated to, then stripped of a dedication to:",
       ["Napoleon Bonaparte", "Prince Lichnowsky", "Archduke Rudolph", "Emperor Joseph II"],
       "Napoleon Bonaparte",
       "Beethoven scratched out the name when Napoleon declared himself emperor in 1804."),
    mc("cl-c05", C,
       "Which of J. S. Bach's sons was the leading figure of the empfindsamer Stil?",
       ["C. P. E. Bach", "J. C. Bach", "W. F. Bach", "J. C. F. Bach"],
       "C. P. E. Bach",
       "His 'sensitive style' prized sudden shifts of feeling; Haydn studied his keyboard works.",
       level=A),
    fb("cl-c06", C,
       "Gluck's operatic reforms are set out in the preface to his 1762 opera ______ ed Euridice.",
       "Orfeo",
       "Gluck sought 'beautiful simplicity', curbing da capo display in favour of drama.",
       accepted=("orfeo", "orpheus", "orfeo ed euridice"), level=A),

    mc("cl-f01", F,
       "The three main sections of sonata form are exposition, development and:",
       ["Recapitulation", "Coda", "Ritornello", "Trio"],
       "Recapitulation",
       "The recapitulation resolves the second subject into the tonic."),
    mc("cl-f02", F,
       "A Classical string quartet consists of:",
       ["Two violins, viola and cello", "Violin, viola, cello and bass", "Two violins and two cellos", "Violin, two violas and cello"],
       "Two violins, viola and cello",
       "Haydn's Op. 33 set is often taken as the form's maturity."),
    mc("cl-f03", F,
       "The typical third movement of a Classical symphony is a:",
       ["Minuet and trio", "Fugue", "Theme and variations", "Passacaglia"],
       "Minuet and trio",
       "Beethoven increasingly replaced it with a faster scherzo."),
    mc("cl-f04", F,
       "In a Classical concerto, the double exposition means:",
       ["Orchestra and soloist each present the themes", "The development occurs twice", "The finale repeats", "Two soloists alternate"],
       "Orchestra and soloist each present the themes",
       "A vestige of Baroque ritornello practice."),
    mc("cl-f05", F,
       "Rondo form is characterized by:",
       ["A recurring refrain alternating with episodes", "Continuous variation", "Strict imitation", "Through-composition"],
       "A recurring refrain alternating with episodes",
       "ABACA or ABACABA; a favourite for finales."),
    mc("cl-f06", F,
       "The cadenza in a Classical concerto traditionally falls:",
       ["Near the end of a movement, over a tonic six-four", "At the very opening", "Between movements", "After the final chord"],
       "Near the end of a movement, over a tonic six-four",
       "Originally improvised; Beethoven began writing them out.",
       level=A),

    mc("cl-t01", T,
       "The Classical style favours which texture?",
       ["Homophony", "Imitative polyphony", "Monophony", "Heterophony"],
       "Homophony",
       "Melody with accompaniment, in clear balanced phrases."),
    mc("cl-t02", T,
       "The broken-chord accompaniment figure common in Classical keyboard music is the ______ bass.",
       ["Alberti", "Murky", "Walking", "Drone"],
       "Alberti",
       "Named for Domenico Alberti; the pattern is low-high-middle-high."),
    mc("cl-t03", T,
       "A period in Classical phrase structure consists of:",
       ["An antecedent and a consequent phrase", "Three equal phrases", "A fugal exposition", "An unmeasured introduction"],
       "An antecedent and a consequent phrase",
       "Usually 4 + 4 bars, the first ending open, the second closed."),
    mc("cl-t04", T,
       "Galant style is best described as:",
       ["Light, elegant and tuneful", "Dense and contrapuntal", "Harsh and dissonant", "Improvised and unmeasured"],
       "Light, elegant and tuneful",
       "A conscious reaction against late Baroque complexity."),
    mc("cl-t05", T,
       "Sturm und Drang in music refers to:",
       ["A turbulent minor-key manner of the 1770s", "A dance form", "A tuning system", "An opera house"],
       "A turbulent minor-key manner of the 1770s",
       "Haydn's Symphony No. 49 'La Passione' is a well-known example.",
       level=A),
    fb("cl-t06", T,
       "Opera buffa is comic Italian opera; its serious counterpart is opera ______.",
       "seria",
       "Opera seria drew on mythological and heroic subjects and favoured da capo arias.",
       accepted=("seria", "opera seria")),

    mc("cl-x01", X,
       "The Classical era coincides with which intellectual movement?",
       ["The Enlightenment", "The Reformation", "Romanticism", "Humanism"],
       "The Enlightenment",
       "Reason, clarity and balance in thought have obvious musical parallels."),
    mc("cl-x02", X,
       "Which two revolutions frame the period politically?",
       ["The American and French Revolutions", "The Industrial and Russian", "The Glorious and Haitian", "The English Civil War and 1848"],
       "The American and French Revolutions",
       "1776 and 1789 - both feed the era's rhetoric of liberty."),
    mc("cl-x03", X,
       "Mozart's move to Vienna in 1781 is significant because he became:",
       ["One of the first prominent freelance composers", "Court Kapellmeister", "A cathedral organist", "An opera impresario"],
       "One of the first prominent freelance composers",
       "He lived on teaching, publishing and subscription concerts rather than a single patron."),
    mc("cl-x04", X,
       "The instrument that displaced the harpsichord during this era was the:",
       ["Fortepiano", "Clavichord", "Organ", "Celesta"],
       "Fortepiano",
       "Its hammer action allowed dynamic shading within a phrase."),
    mc("cl-x05", X,
       "The Mannheim orchestra was celebrated for:",
       ["Its disciplined crescendos and ensemble", "Its use of period instruments", "Its all-female membership", "Its opera productions"],
       "Its disciplined crescendos and ensemble",
       "The 'Mannheim rocket' and 'Mannheim steamroller' entered the common style.",
       level=A),
]
