"""The Middle Ages, ad 476 - ad 1450."""

from ..models import (
    CATEGORY_COMPOSERS as C,
    CATEGORY_CONTEXT as X,
    CATEGORY_FORMS as F,
    CATEGORY_TERMS as T,
)
from ._builders import LEVEL_ARCT as A, fb, mc

QUESTIONS = [
    # --- Composers -----------------------------------------------------------
    mc("ma-c01", C,
       "Which 12th-century German abbess composed the morality play Ordo Virtutum?",
       ["Hildegard von Bingen", "Herrad of Landsberg", "Marie de France", "Beatriz de Dia"],
       "Hildegard von Bingen",
       "Hildegard (1098-1179) led the convent at Rupertsberg. Ordo Virtutum is the earliest surviving morality play set to music."),
    mc("ma-c02", C,
       "Leonin and Perotin are the two composers associated with which school?",
       ["The Notre Dame School", "The Burgundian School", "The Roman School", "The Venetian School"],
       "The Notre Dame School",
       "Both worked at Notre Dame in Paris c. 1160-1250, the centre of early measured polyphony."),
    mc("ma-c03", C,
       "Who composed the Messe de Nostre Dame, the first complete polyphonic Mass Ordinary by a single known composer?",
       ["Guillaume de Machaut", "Philippe de Vitry", "Francesco Landini", "Guillaume Dufay"],
       "Guillaume de Machaut",
       "Machaut (c. 1300-1377) was the leading Ars Nova figure, a poet and cleric as well as a composer."),
    mc("ma-c04", C,
       "Which blind Italian organist and composer was the leading figure of the Italian Trecento?",
       ["Francesco Landini", "Jacopo da Bologna", "Adam de la Halle", "Perotin"],
       "Francesco Landini",
       "Landini (c. 1325-1397) was blinded by smallpox as a child; the 'Landini cadence' carries his name."),
    mc("ma-c05", C,
       "Who wrote the treatise Ars Nova (c. 1322), which gave the era its name?",
       ["Philippe de Vitry", "Guido d'Arezzo", "Leonin", "Franco of Cologne"],
       "Philippe de Vitry",
       "De Vitry's treatise codified new rhythmic notation, including duple division of the beat."),
    mc("ma-c06", C,
       "Adam de la Halle's Le Jeu de Robin et de Marion is best described as an early example of what?",
       ["A secular musical play", "A polyphonic Mass", "An isorhythmic motet", "A liturgical drama"],
       "A secular musical play",
       "Written c. 1284, it interleaves spoken dialogue with popular songs - a distant ancestor of comic opera."),
    fb("ma-c07", C,
       "The monk who devised the four-line staff and the syllables ut-re-mi-fa-sol-la was Guido d'______.",
       "Arezzo",
       "Guido d'Arezzo (c. 991-1033) also devised the 'Guidonian hand' for teaching sight-singing.",
       accepted=("arezzo", "guido d'arezzo", "guido of arezzo")),
    mc("ma-c08", C,
       "Which class of poet-musician served the courts of southern France, singing in Occitan?",
       ["Troubadours", "Trouveres", "Minnesingers", "Goliards"],
       "Troubadours",
       "Troubadours sang in Occitan in the south; trouveres were their northern counterparts, singing in Old French.",
       level=A),

    # --- Forms ---------------------------------------------------------------
    mc("ma-f01", F,
       "What is the name for the monophonic, unaccompanied sacred song of the medieval Roman Church?",
       ["Plainchant", "Organum", "Conductus", "Estampie"],
       "Plainchant",
       "Also called Gregorian chant, after Pope Gregory I, to whom it was traditionally but wrongly attributed."),
    mc("ma-f02", F,
       "Organum in its earliest form consisted of a chant melody with an added voice moving in what manner?",
       ["Parallel motion at a fixed interval", "Free imitation", "Contrary motion only", "Homophonic block chords"],
       "Parallel motion at a fixed interval",
       "Parallel organum doubled the chant at the fourth or fifth; it is first described in the Musica enchiriadis (c. 900)."),
    mc("ma-f03", F,
       "The medieval motet originated by adding text to which pre-existing part?",
       ["The upper voice of a clausula", "The bass line of a Mass", "An instrumental dance", "A troubadour chanson"],
       "The upper voice of a clausula",
       "'Motet' comes from the French mot, 'word' - text was fitted to a discant clausula's upper voice."),
    mc("ma-f04", F,
       "Which of these is a medieval instrumental dance form?",
       ["Estampie", "Conductus", "Organum", "Sequence"],
       "Estampie",
       "The estampie is among the earliest surviving notated instrumental music, from the 13th-14th centuries."),
    mc("ma-f05", F,
       "The formes fixes of 14th-century French song were the ballade, the virelai and the ______.",
       ["Rondeau", "Madrigal", "Caccia", "Lauda"],
       "Rondeau",
       "Each fixed form has its own repeating refrain scheme; Machaut wrote extensively in all three."),
    mc("ma-f06", F,
       "A conductus differs from a motet chiefly because its tenor is:",
       ["Newly composed rather than borrowed chant", "Sung by instruments only", "Always in triple metre", "Texted in the vernacular"],
       "Newly composed rather than borrowed chant",
       "Conductus voices are also typically texted alike and move in similar rhythm, unlike the motet's layered texts."),
    fb("ma-f07", F,
       "The Italian 14th-century form in which two voices sing the same text in strict canon over a free tenor is the ______.",
       "caccia",
       "Caccia means 'hunt' - the voices chase one another, and the texts often depict hunting or market scenes.",
       accepted=("caccia", "the caccia"), level=A),

    # --- Terminology ---------------------------------------------------------
    mc("ma-t01", T,
       "A texture of a single melodic line with no accompaniment is called:",
       ["Monophony", "Homophony", "Polyphony", "Heterophony"],
       "Monophony",
       "Plainchant is the defining monophonic repertoire of the Middle Ages."),
    mc("ma-t02", T,
       "Many notes sung to a single syllable of text is described as:",
       ["Melismatic", "Syllabic", "Neumatic", "Strophic"],
       "Melismatic",
       "Syllabic is one note per syllable; neumatic is roughly two to four."),
    mc("ma-t03", T,
       "The early notation signs that indicated melodic shape without precise pitch were called:",
       ["Neumes", "Clefs", "Ligatures", "Custos"],
       "Neumes",
       "Neumes reminded a singer of a melody already known; exact pitch required Guido's staff."),
    mc("ma-t04", T,
       "In a medieval motet, the borrowed chant melody placed in the lowest voice is the:",
       ["Cantus firmus", "Descant", "Contratenor", "Triplum"],
       "Cantus firmus",
       "Literally 'fixed song' - the pre-existing melody the other voices are built against."),
    mc("ma-t05", T,
       "The six-note scale segment used in medieval solmization was the:",
       ["Hexachord", "Tetrachord", "Pentachord", "Octachord"],
       "Hexachord",
       "Ut-re-mi-fa-sol-la; moving between overlapping hexachords was called mutation."),
    mc("ma-t06", T,
       "Isorhythm is the repetition of a rhythmic pattern called the ______ against a repeating melodic pattern called the color.",
       ["Talea", "Tenor", "Modus", "Ordo"],
       "Talea",
       "Talea and color need not be the same length, which is what makes isorhythmic structures so intricate.",
       level=A),
    mc("ma-t07", T,
       "Hocket is a technique in which:",
       ["A melody is split between voices by rapid alternation", "A voice sustains one long note", "Two voices sing in parallel fifths", "A chant is sung twice as slowly"],
       "A melody is split between voices by rapid alternation",
       "From the French hoquet, 'hiccup' - one voice rests while the other sounds, in quick alternation.",
       level=A),
    mc("ma-t08", T,
       "The eight medieval church modes are distinguished from one another by their:",
       ["Final and range", "Key signature", "Time signature", "Tempo marking"],
       "Final and range",
       "Each mode pairs an authentic form with a plagal form sharing the same final but sitting a fourth lower."),
    fb("ma-t09", T,
       "The practice of raising or lowering notes by unwritten accidentals, left to the performer, is called musica ______.",
       "ficta",
       "Musica ficta means 'feigned music' - notes outside the written gamut, applied by convention.",
       accepted=("ficta", "musica ficta"), level=A),
    mc("ma-t10", T,
       "The system of rhythmic modes used at Notre Dame organized rhythm into repeating patterns of:",
       ["Longs and breves", "Whole and half notes", "Dotted rhythms only", "Free unmeasured values"],
       "Longs and breves",
       "Six modal patterns, all in triple groupings, reflecting the 'perfection' of the number three."),

    # --- Historical context --------------------------------------------------
    mc("ma-x01", X,
       "The Middle Ages are conventionally dated from the fall of which empire?",
       ["The Western Roman Empire", "The Byzantine Empire", "The Holy Roman Empire", "The Carolingian Empire"],
       "The Western Roman Empire",
       "The traditional date is ad 476, when the last Western Roman emperor was deposed."),
    mc("ma-x02", X,
       "Through most of the Middle Ages, the chief patron and preserver of notated music was:",
       ["The Church", "The merchant guilds", "Public concert societies", "Music publishers"],
       "The Church",
       "Monasteries copied and taught the repertoire; almost all surviving early manuscripts are sacred."),
    mc("ma-x03", X,
       "Which building's construction coincided with the rise of measured polyphony in Paris?",
       ["Notre Dame Cathedral", "Chartres Cathedral", "St Mark's Basilica", "Westminster Abbey"],
       "Notre Dame Cathedral",
       "Begun in 1163, it gave its name to the school of Leonin and Perotin."),
    mc("ma-x04", X,
       "The Black Death, which reshaped 14th-century European life, struck around:",
       ["1347-1351", "1215-1220", "1410-1415", "1290-1295"],
       "1347-1351",
       "It killed perhaps a third of Europe's population, and its shadow falls across late Ars Nova texts."),
    mc("ma-x05", X,
       "Ars Antiqua and Ars Nova are terms distinguishing music of which centuries respectively?",
       ["13th and 14th", "11th and 12th", "14th and 15th", "12th and 13th"],
       "13th and 14th",
       "Ars Nova brought duple division of note values and far greater rhythmic freedom."),
    mc("ma-x06", X,
       "The Roman de Fauvel (1310-1314) is significant to music historians because it:",
       ["Preserves many early Ars Nova motets", "Is the first printed music book", "Contains the earliest opera", "Records troubadour biographies"],
       "Preserves many early Ars Nova motets",
       "Its illuminated manuscript interpolates 169 musical pieces, several attributed to Philippe de Vitry.",
       level=A),
    fb("ma-x07", X,
       "The travelling entertainers of the medieval period, of low social standing, were known as ______.",
       "jongleurs",
       "Jongleurs performed but generally did not compose; troubadours and trouveres, by contrast, were often noble.",
       accepted=("jongleurs", "jongleur", "minstrels")),
]
