"""The twentieth century and beyond, 1900 - present."""

from ..models import (
    CATEGORY_COMPOSERS as C,
    CATEGORY_CONTEXT as X,
    CATEGORY_FORMS as F,
    CATEGORY_TERMS as T,
)
from ._builders import LEVEL_ARCT as A, fb, mc

QUESTIONS = [
    mc("mo-c01", C,
       "Whose Le Sacre du printemps caused a riot at its 1913 Paris premiere?",
       ["Igor Stravinsky", "Claude Debussy", "Maurice Ravel", "Erik Satie"],
       "Igor Stravinsky",
       "The Rite of Spring's pounding irregular metres and dissonance overwhelmed the audience."),
    mc("mo-c02", C,
       "Which composer devised the twelve-tone method in the early 1920s?",
       ["Arnold Schoenberg", "Alban Berg", "Anton Webern", "Paul Hindemith"],
       "Arnold Schoenberg",
       "A method of composing with twelve tones related only to one another, replacing tonal hierarchy."),
    mc("mo-c03", C,
       "Debussy's Prelude a l'apres-midi d'un faune is a landmark of which style?",
       ["Impressionism", "Expressionism", "Neoclassicism", "Minimalism"],
       "Impressionism",
       "Whole-tone and modal colour, blurred rhythm, and orchestration as atmosphere."),
    mc("mo-c04", C,
       "Which Hungarian composer collected and transcribed thousands of folk melodies?",
       ["Bela Bartok", "Zoltan Kodaly", "Leos Janacek", "Karol Szymanowski"],
       "Bela Bartok",
       "Bartok and Kodaly both did fieldwork, but Bartok's ethnomusicology was the more systematic."),
    mc("mo-c05", C,
       "John Cage's 4'33\" consists of:",
       ["Four minutes 33 seconds of notated silence", "A twelve-tone row", "Prepared piano clusters", "Taped electronic sound"],
       "Four minutes 33 seconds of notated silence",
       "The ambient sound of the room becomes the piece."),
    mc("mo-c06", C,
       "Which American composer fused jazz idioms with concert forms in Rhapsody in Blue?",
       ["George Gershwin", "Aaron Copland", "Charles Ives", "Leonard Bernstein"],
       "George Gershwin",
       "Premiered 1924 in Paul Whiteman's 'Experiment in Modern Music' concert."),
    mc("mo-c07", C,
       "The Second Viennese School comprised Schoenberg and his pupils:",
       ["Berg and Webern", "Bartok and Kodaly", "Ravel and Debussy", "Hindemith and Weill"],
       "Berg and Webern",
       "Berg kept a lyric, quasi-tonal warmth; Webern pared everything to aphorism.",
       level=A),
    fb("mo-c08", C,
       "The American minimalist who wrote Music for 18 Musicians is Steve ______.",
       "Reich",
       "Reich's phasing technique grew out of experiments with tape loops drifting apart.",
       accepted=("reich", "steve reich"), level=A),

    mc("mo-f01", F,
       "Musique concrete is music built from:",
       ["Recorded natural sounds manipulated on tape", "Twelve-tone rows", "Folk melodies", "Improvised jazz"],
       "Recorded natural sounds manipulated on tape",
       "Pierre Schaeffer began the practice at French radio in 1948."),
    mc("mo-f02", F,
       "Aleatoric music is music in which:",
       ["Some elements are left to chance", "Every note is serialized", "The metre never changes", "Only percussion is used"],
       "Some elements are left to chance",
       "From alea, 'dice'. Cage and Lutoslawski used chance very differently."),
    mc("mo-f03", F,
       "Minimalism is characterized by:",
       ["Repetitive patterns and gradual process", "Dense chromatic saturation", "Strict fugal writing", "Free atonality"],
       "Repetitive patterns and gradual process",
       "Riley, Reich, Glass and Adams are the usual names."),
    mc("mo-f04", F,
       "Neoclassicism in the 1920s involved:",
       ["Reworking 18th-century forms with modern harmony", "Reviving Gregorian chant", "Abandoning notation", "Writing only for electronics"],
       "Reworking 18th-century forms with modern harmony",
       "Stravinsky's Pulcinella is the emblematic turn."),
    mc("mo-f05", F,
       "Total serialism extends row technique to:",
       ["Rhythm, dynamics and articulation as well as pitch", "Pitch only", "Text setting", "Orchestration only"],
       "Rhythm, dynamics and articulation as well as pitch",
       "Messiaen's Mode de valeurs pointed the way; Boulez and Stockhausen pursued it.",
       level=A),

    mc("mo-t01", T,
       "Atonality means music that:",
       ["Avoids a tonal centre", "Has no rhythm", "Uses only white keys", "Is unnotated"],
       "Avoids a tonal centre",
       "Schoenberg preferred 'pantonal', disliking the negative prefix."),
    mc("mo-t02", T,
       "Polytonality is:",
       ["Two or more keys sounding at once", "Rapid key changes", "Music with no key signature", "A scale of ten notes"],
       "Two or more keys sounding at once",
       "Milhaud and the Petrushka chord are standard illustrations."),
    mc("mo-t03", T,
       "Sprechstimme is:",
       ["A vocal delivery between speech and song", "A string technique", "A form of canon", "A tuning system"],
       "A vocal delivery between speech and song",
       "Schoenberg used it throughout Pierrot lunaire (1912)."),
    mc("mo-t04", T,
       "A tone cluster is:",
       ["A chord of adjacent seconds", "A twelve-tone row", "An inverted triad", "A percussion roll"],
       "A chord of adjacent seconds",
       "Henry Cowell played them with forearm and fist."),
    mc("mo-t05", T,
       "Prepared piano refers to a piano whose:",
       ["Strings are altered with inserted objects", "Lid is removed", "Strings are retuned a quarter tone flat", "Hammers are amplified"],
       "Strings are altered with inserted objects",
       "Cage inserted bolts, screws and rubber to turn the piano into a percussion orchestra."),
    fb("mo-t06", T,
       "The metre that changes bar to bar, common in Stravinsky, is called ______ metre.",
       "changing",
       "Also called mixed or asymmetric metre; the Rite's Danse sacrale is the classic case.",
       accepted=("changing", "mixed", "asymmetric", "irregular")),

    mc("mo-x01", X,
       "Which technology most changed how twentieth-century audiences encountered music?",
       ["Sound recording", "Music printing", "The valve", "Equal temperament"],
       "Sound recording",
       "Performance became repeatable and portable, and a canon formed around recordings."),
    mc("mo-x02", X,
       "Under Soviet cultural policy, composers such as Shostakovich were pressured to write in a style called:",
       ["Socialist realism", "Futurism", "Serialism", "Neoclassicism"],
       "Socialist realism",
       "Accessible, optimistic and patriotic; Shostakovich was denounced in 1936 and again in 1948."),
    mc("mo-x03", X,
       "Jazz emerged in the early twentieth century principally from:",
       ["African American communities in New Orleans", "Viennese salons", "Parisian conservatories", "London music halls"],
       "African American communities in New Orleans",
       "Blues and ragged rhythm fed a new improvised ensemble practice."),
    mc("mo-x04", X,
       "Which composer's Quartet for the End of Time was written and premiered in a prisoner-of-war camp?",
       ["Olivier Messiaen", "Francis Poulenc", "Benjamin Britten", "Dmitri Shostakovich"],
       "Olivier Messiaen",
       "Composed at Stalag VIII-A and first played in 1941 for fellow prisoners.",
       level=A),
]
