"""The Renaissance, 1450 - 1600."""

from ..models import (
    CATEGORY_COMPOSERS as C,
    CATEGORY_CONTEXT as X,
    CATEGORY_FORMS as F,
    CATEGORY_TERMS as T,
)
from ._builders import LEVEL_ARCT as A, fb, mc

QUESTIONS = [
    mc("re-c01", C,
       "Which Franco-Flemish composer is regarded as the leading figure of the High Renaissance?",
       ["Josquin des Prez", "Guillaume Dufay", "John Dunstaple", "Orlande de Lassus"],
       "Josquin des Prez",
       "Josquin (c. 1450-1521) was praised by Luther as 'master of the notes'."),
    mc("re-c02", C,
       "Palestrina's Pope Marcellus Mass is traditionally linked to which event?",
       ["The Council of Trent", "The Diet of Worms", "The Peace of Augsburg", "The Edict of Nantes"],
       "The Council of Trent",
       "Legend says it proved polyphony could keep sacred text intelligible, saving it from banishment."),
    mc("re-c03", C,
       "Which English composer wrote both Latin motets and Anglican services under Elizabeth I?",
       ["William Byrd", "Henry Purcell", "John Dowland", "Thomas Morley"],
       "William Byrd",
       "Byrd remained Catholic while serving the Protestant Chapel Royal - a remarkable tolerance."),
    mc("re-c04", C,
       "Giovanni Gabrieli is associated with the polychoral music of which building?",
       ["St Mark's, Venice", "Notre Dame, Paris", "St Peter's, Rome", "King's College, Cambridge"],
       "St Mark's, Venice",
       "Its opposing galleries inspired cori spezzati - 'broken choirs' answering one another."),
    fb("re-c05", C,
       "The English lutenist-songwriter famous for 'Flow, my tears' was John ______.",
       "Dowland",
       "Dowland's melancholy ayres were among the most widely circulated songs of the age.",
       accepted=("dowland", "john dowland")),
    mc("re-c06", C,
       "Which composer wrote over 2,000 works and served the Bavarian court at Munich?",
       ["Orlande de Lassus", "Josquin des Prez", "Jacob Obrecht", "Clement Janequin"],
       "Orlande de Lassus",
       "Lassus (c. 1532-1594) was the most cosmopolitan and prolific composer of the late Renaissance.",
       level=A),

    mc("re-f01", F,
       "The principal secular vocal form of the Italian Renaissance was the:",
       ["Madrigal", "Motet", "Chanson", "Ricercar"],
       "Madrigal",
       "Through-composed and word-driven, it spread to England in the 1580s."),
    mc("re-f02", F,
       "A Mass that borrows and reworks multiple voices of a pre-existing polyphonic piece is called a:",
       ["Parody Mass", "Cantus firmus Mass", "Paraphrase Mass", "Requiem Mass"],
       "Parody Mass",
       "Also called an imitation Mass; it quotes whole textures, not just one line.",
       level=A),
    mc("re-f03", F,
       "Which instrumental form is an imitative precursor to the fugue?",
       ["Ricercar", "Estampie", "Toccata", "Pavane"],
       "Ricercar",
       "From ricercare, 'to seek out' - a point of imitation explored through the voices."),
    mc("re-f04", F,
       "The pavane and galliard were typically performed as:",
       ["A paired slow and fast dance", "Two unrelated sacred pieces", "Vocal madrigals", "Organ preludes"],
       "A paired slow and fast dance",
       "A stately duple pavane followed by a lively triple galliard - an ancestor of the suite."),
    mc("re-f05", F,
       "The Lutheran congregational hymn developed during the Reformation is the:",
       ["Chorale", "Anthem", "Motet", "Lauda"],
       "Chorale",
       "Sung in German by the whole congregation, later the backbone of Bach's church music."),

    mc("re-t01", T,
       "Word painting means:",
       ["Music that mirrors the meaning of the text", "Illuminating a manuscript", "Writing lyrics before music", "Notating without a staff"],
       "Music that mirrors the meaning of the text",
       "A rising line on 'ascend', a dissonance on 'pain' - the madrigal's defining device."),
    mc("re-t02", T,
       "A texture in which voices enter successively with the same melodic idea is called:",
       ["Imitative polyphony", "Homorhythm", "Monody", "Heterophony"],
       "Imitative polyphony",
       "Points of imitation are the structural unit of the Renaissance motet."),
    mc("re-t03", T,
       "A cappella means:",
       ["Unaccompanied vocal music", "With full orchestra", "In the chapel style with organ", "Sung by soloists only"],
       "Unaccompanied vocal music",
       "Literally 'in the manner of the chapel'."),
    mc("re-t04", T,
       "Musica reservata refers to:",
       ["An expressive, text-sensitive style for connoisseurs", "Music reserved for royalty", "Reserved seating at concerts", "Music kept in manuscript"],
       "An expressive, text-sensitive style for connoisseurs",
       "A 16th-century term for refined, affect-driven writing.",
       level=A),
    fb("re-t05", T,
       "The Renaissance consort of recorders or viols of different sizes playing together is called a ______ consort.",
       "whole",
       "A whole consort is one family of instruments; a broken consort mixes families.",
       accepted=("whole", "whole consort")),

    mc("re-x01", X,
       "Which technology most transformed the spread of music after 1501?",
       ["Music printing", "The pianoforte", "Sound recording", "The metronome"],
       "Music printing",
       "Ottaviano Petrucci's Odhecaton (1501) was the first printed polyphonic collection."),
    mc("re-x02", X,
       "The Reformation was set in motion in 1517 by:",
       ["Martin Luther", "John Calvin", "Henry VIII", "Erasmus"],
       "Martin Luther",
       "Luther, himself a musician, gave music a central role in Lutheran worship."),
    mc("re-x03", X,
       "The Council of Trent (1545-1563) addressed music by:",
       ["Demanding clearer text setting in sacred works", "Banning all polyphony", "Requiring vernacular Masses", "Introducing equal temperament"],
       "Demanding clearer text setting in sacred works",
       "It objected to florid polyphony obscuring liturgical words, and to secular borrowings."),
    mc("re-x04", X,
       "Renaissance humanism affected music chiefly by encouraging:",
       ["Greater attention to text and human expression", "Longer Masses", "Abandonment of notation", "Exclusively instrumental music"],
       "Greater attention to text and human expression",
       "The recovery of classical writings put rhetoric and the affections at the centre of composition."),
    mc("re-x05", X,
       "The Florentine Camerata, active in the 1580s, is important because its experiments led to:",
       ["Opera", "The symphony", "The string quartet", "The fugue"],
       "Opera",
       "Their attempt to revive Greek drama produced monody and, by 1600, the first operas.",
       level=A),
]
