"""The Romantic era, 1825 - 1900."""

from ..models import (
    CATEGORY_COMPOSERS as C,
    CATEGORY_CONTEXT as X,
    CATEGORY_FORMS as F,
    CATEGORY_TERMS as T,
)
from ._builders import LEVEL_ARCT as A, fb, mc

QUESTIONS = [
    mc("ro-c01", C,
       "Which composer wrote over 600 Lieder, including the cycle Winterreise?",
       ["Franz Schubert", "Robert Schumann", "Hugo Wolf", "Johannes Brahms"],
       "Franz Schubert",
       "Schubert died at 31, having largely invented the German art song as we know it."),
    mc("ro-c02", C,
       "Chopin's output is dominated by works for:",
       ["Solo piano", "String quartet", "Opera", "Organ"],
       "Solo piano",
       "Mazurkas, polonaises, nocturnes and ballades - almost nothing without piano."),
    mc("ro-c03", C,
       "Which composer invented the symphonic poem and pioneered thematic transformation?",
       ["Franz Liszt", "Hector Berlioz", "Richard Wagner", "Cesar Franck"],
       "Franz Liszt",
       "A single-movement orchestral form built on an extra-musical idea."),
    mc("ro-c04", C,
       "Wagner's four-opera cycle Der Ring des Nibelungen was first staged complete at:",
       ["Bayreuth", "Vienna", "Milan", "Dresden"],
       "Bayreuth",
       "In 1876, in a theatre Wagner designed for his own works."),
    mc("ro-c05", C,
       "Berlioz's Symphonie fantastique is famous for its recurring theme, the:",
       ["Idee fixe", "Leitmotif", "Cantus firmus", "Ground bass"],
       "Idee fixe",
       "It represents the beloved, transformed in each movement."),
    mc("ro-c06", C,
       "Which Russian group sought a national style free of German training?",
       ["The Mighty Handful", "Les Six", "The Second Viennese School", "The Florentine Camerata"],
       "The Mighty Handful",
       "Balakirev, Cui, Mussorgsky, Rimsky-Korsakov and Borodin - also called The Five.",
       level=A),
    fb("ro-c07", C,
       "The composer of the Hungarian-inflected Hungarian Dances and the German Requiem was Johannes ______.",
       "Brahms",
       "Brahms was seen as the classicist counterweight to the Liszt-Wagner 'New German School'.",
       accepted=("brahms", "johannes brahms")),
    mc("ro-c08", C,
       "Clara Schumann is significant as:",
       ["A leading concert pianist and composer", "An opera librettist", "A violin maker", "A music publisher"],
       "A leading concert pianist and composer",
       "Her sixty-year performing career shaped the modern solo recital."),

    mc("ro-f01", F,
       "A Lied is:",
       ["A German art song for voice and piano", "A short piano piece", "A choral Mass", "An orchestral overture"],
       "A German art song for voice and piano",
       "The piano is an equal partner, not mere accompaniment."),
    mc("ro-f02", F,
       "A song cycle is:",
       ["A group of songs linked by narrative or theme", "A song repeated in all keys", "A round", "A set of variations"],
       "A group of songs linked by narrative or theme",
       "Schumann's Dichterliebe and Schubert's Die schone Mullerin are standard examples."),
    mc("ro-f03", F,
       "Character piece is the term for:",
       ["A short piano work evoking a mood or scene", "An operatic aria", "A symphonic finale", "A study in counterpoint"],
       "A short piano work evoking a mood or scene",
       "Nocturnes, intermezzi, impromptus and songs without words all qualify."),
    mc("ro-f04", F,
       "Program music is music that:",
       ["Depicts an extra-musical story or image", "Is printed in a concert program", "Follows strict sonata form", "Is written for teaching"],
       "Depicts an extra-musical story or image",
       "Its opposite, absolute music, was championed by Hanslick and Brahms."),
    mc("ro-f05", F,
       "A leitmotif is:",
       ["A recurring theme tied to a character or idea", "The opening of a symphony", "A cadential formula", "A vocal ornament"],
       "A recurring theme tied to a character or idea",
       "Wagner wove them through the orchestral fabric of his music dramas."),
    mc("ro-f06", F,
       "Verismo opera is characterized by:",
       ["Gritty, everyday subjects", "Mythological plots", "Spoken dialogue only", "Baroque revival forms"],
       "Gritty, everyday subjects",
       "Mascagni's Cavalleria rusticana and Leoncavallo's Pagliacci are the models.",
       level=A),

    mc("ro-t01", T,
       "Rubato means:",
       ["Flexible, expressive treatment of tempo", "Very loud", "Muted strings", "A rapid scale"],
       "Flexible, expressive treatment of tempo",
       "Literally 'robbed' time - taken from one beat and repaid to another."),
    mc("ro-t02", T,
       "Chromaticism refers to:",
       ["Extensive use of notes outside the key", "Playing on black keys", "Colourful orchestration", "Bright dynamics"],
       "Extensive use of notes outside the key",
       "Wagner's Tristan chord is the era's emblem of harmonic ambiguity."),
    mc("ro-t03", T,
       "Nationalism in Romantic music typically drew on:",
       ["Folk songs, dances and native legends", "Latin liturgy", "Greek modes", "Court dances"],
       "Folk songs, dances and native legends",
       "Smetana, Dvorak, Grieg and Sibelius all built idioms this way."),
    mc("ro-t04", T,
       "An augmented sixth chord resolving outward to the dominant is a hallmark of Romantic:",
       ["Harmony", "Orchestration", "Form", "Notation"],
       "Harmony",
       "Italian, French and German varieties differ by their added tone.",
       level=A),
    fb("ro-t05", T,
       "The total art work uniting music, poetry and staging that Wagner theorized is the ______.",
       "Gesamtkunstwerk",
       "Wagner set out the idea in his 1849 essay The Artwork of the Future.",
       accepted=("gesamtkunstwerk", "total art work", "total artwork"), level=A),

    mc("ro-x01", X,
       "Romantic composers increasingly earned a living through:",
       ["Public concerts, publishing and teaching", "Church appointments only", "Royal salaries only", "Guild membership"],
       "Public concerts, publishing and teaching",
       "A growing middle-class audience replaced aristocratic patronage."),
    mc("ro-x02", X,
       "Which invention most enlarged the Romantic orchestra's brass section?",
       ["The valve", "The mute", "The reed", "The pedal"],
       "The valve",
       "Valves gave horns and trumpets a full chromatic scale from the 1830s."),
    mc("ro-x03", X,
       "The virtuoso whose showmanship on the violin defined the Romantic performer was:",
       ["Niccolo Paganini", "Joseph Joachim", "Pablo Sarasate", "Henri Vieuxtemps"],
       "Niccolo Paganini",
       "His technical feats fed rumours of a pact with the devil - and inspired Liszt."),
    mc("ro-x04", X,
       "The Industrial Revolution affected music partly by making which instrument affordable to middle-class homes?",
       ["The piano", "The harp", "The organ", "The harpsichord"],
       "The piano",
       "Iron frames and mass production put a piano in the parlour, creating a huge sheet-music market."),
]
