# Generated by Django 6.0.7 on 2026-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('composer', models.CharField(db_index=True, max_length=300)),
                ('rating', models.FloatField(default=0)),
                ('pdmx_path', models.CharField(max_length=500, unique=True)),
                ('musicxml_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('part_count', models.PositiveIntegerField()),
                ('measure_count', models.PositiveIntegerField()),
                ('time_signature', models.CharField(blank=True, max_length=20)),
                ('tempo_bpm', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', 'title'],
            },
        ),
    ]
